CREATE TABLE IF NOT EXISTS TENANT_staging.rx_claim (
    row_id VARCHAR,
    claim_type VARCHAR,
    claim_id VARCHAR,
    previous_claim_id VARCHAR,
    claim_disposition VARCHAR,
    member_id VARCHAR,
    member_mbi VARCHAR,
    member_medicaid_id VARCHAR,
    alternate_member_id VARCHAR,
    subscriber_id VARCHAR,
    member_id_suffix VARCHAR,
    member_ssn VARCHAR,
    member_mrn VARCHAR,
    member_internal_id VARCHAR,
    member_last_name VARCHAR,
    member_first_name VARCHAR,
    member_middle_initial VARCHAR,
    member_dob DATE,
    member_gender VARCHAR,
    member_relationship_code VARCHAR,
    member_address_line_1 VARCHAR,
    member_address_line_2 VARCHAR,
    member_city VARCHAR,
    member_state VARCHAR,
    member_zip VARCHAR,
    insurance_company_name VARCHAR,
    insurance_company_id VARCHAR,
    insurance_group_name VARCHAR,
    insurance_group_id VARCHAR,
    insurance_group_plan_name VARCHAR,
    insurance_group_plan_id VARCHAR,
    primary_payer_code VARCHAR,
    claim_billed_date TIMESTAMP(3) WITH TIME ZONE,
    claim_start_date TIMESTAMP(3) WITH TIME ZONE,
    claim_end_date TIMESTAMP(3) WITH TIME ZONE,
    claim_total_charges DOUBLE,
    claim_adjudication_status VARCHAR,
    claim_total_paid DOUBLE,
    claim_paid_date TIMESTAMP(3) WITH TIME ZONE,
    network_paid_ind VARCHAR,
    claim_copay_amount DOUBLE,
    claim_patient_paid_amount DOUBLE,
    claim_other_payer_paid DOUBLE,
    line_number VARCHAR,
    line_item_control_number VARCHAR,
    service_line_disposition VARCHAR,
    service_start_date TIMESTAMP(3) WITH TIME ZONE,
    service_end_date TIMESTAMP(3) WITH TIME ZONE,
    service_line_charges DOUBLE,
    line_adjudication_status VARCHAR,
    line_amount_paid DOUBLE,
    service_line_paid_date TIMESTAMP(3) WITH TIME ZONE,
    line_payment_level VARCHAR,
    line_copay_amount DOUBLE,
    line_patient_paid_amount DOUBLE,
    mco_paid_amount DOUBLE,
    prescription_number VARCHAR,
    prescription_date TIMESTAMP(3) WITH TIME ZONE,
    dispense_date TIMESTAMP(3) WITH TIME ZONE,
    daw_code VARCHAR,
    drug_ndc_code VARCHAR,
    drug_ndc_desc VARCHAR,
    generic_branded_ind VARCHAR,
    gpi VARCHAR,
    drug_strength VARCHAR,
    drug_quantity VARCHAR,
    days_supply VARCHAR,
    mail_order_flag VARCHAR,
    provider_org_napb_id VARCHAR,
    line_rendering_participation VARCHAR,
    render_prescriber_npi VARCHAR,
    render_prescriber_internal_id VARCHAR,
    render_prescriber_first_name VARCHAR,
    render_prescriber_last_name VARCHAR,
    render_prescriber_street_line_1 VARCHAR,
    render_prescriber_street_line_2 VARCHAR,
    render_prescriber_city VARCHAR,
    render_prescriber_state VARCHAR,
    render_prescriber_zip VARCHAR,
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://DATA_S3_BUCKET/delta-tables/TENANT/staging/rx_claim',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);