BEGIN;

ALTER TABLE IF EXISTS coverage
    ADD COLUMN IF NOT EXISTS payor_id UUID DEFAULT NULL;

UPDATE coverage SET insurer_id ='00000000-0000-0000-0000-000000000000';

ALTER TABLE IF EXISTS coverage
    ALTER insurer_id SET NOT NULL;

ALTER TABLE IF EXISTS coverage
    DROP COLUMN IF EXISTS insurance_plan_id;

ALTER TABLE IF EXISTS coverage
    DROP COLUMN IF EXISTS insurer_id;

COMMIT;