CREATE TABLE IF NOT EXISTS cynchealth_staging.gap_demographic (
    row_id VARCHAR,
    row VARCHAR,
    domain VARCHAR,
    patient_first_name VARCHAR,
    patient_last_name VARCHAR,
    patient_dob VARCHAR,
    external_patient_id VARCHAR,
    external_practice_id VARCHAR,
    first_name VARCHAR,
    last_name VARCHAR,
    dob VARCHAR,
    middle_name VARCHAR,
    suffix VARCHAR,
    gender VARCHAR,
    race_code VARCHAR,
    race_name VARCHAR,
    race_dictionary VARCHAR,
    ethnicity_code VARCHAR,
    ethnicity_name VARCHAR,    
    ethnicity_dictionary VARCHAR,
    primary_language_code VARCHAR,
    primary_language_name VARCHAR,
    primary_language_dictionary VARCHAR,
    marital_status_code VARCHAR,
    martial_status_name VARCHAR,
    marital_status_dictionary VARCHAR,
    ssn VARCHAR,
    active VARCHAR,
    primary_physician_first_name VARCHAR,
    primary_physician_last_name VARCHAR,
    primary_physician_npi VARCHAR,
    override_pcp VARCHAR,
    other_physician_first_name VARCHAR,
    other_physician_last_name VARCHAR,
    other_physician_npi VARCHAR,
    remove_specified_other_physician VARCHAR,
    home_phone VARCHAR,
    other_phone VARCHAR,
    email VARCHAR,
    home_address_line1 VARCHAR,
    home_address_line2 VARCHAR,
    city VARCHAR,
    state VARCHAR,
    zip VARCHAR,
    patient_provider_partnership VARCHAR,
    patient_provider_partnership_date VARCHAR,
    advance_directives VARCHAR,
    advance_directives_date VARCHAR,
    inactive_reason_code VARCHAR,
    inactive_reason_name VARCHAR,
    inactive_reason_dictionary VARCHAR,
    health_literacy VARCHAR,
    caremanager_first_name VARCHAR,
    caremanager_last_name VARCHAR,
    caremanager_npi VARCHAR,
    remove_specified_caremanager VARCHAR,
    date_of_death VARCHAR,
    reminder_preference VARCHAR,
    last_reminder_date VARCHAR,
    patient_id VARCHAR,
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/cynchealth/staging/gap_demographic',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);
