CREATE TABLE IF NOT EXISTS cynchealth_staging.gap_lab (
    row_id VARCHAR,
    row VARCHAR,
    domain VARCHAR,
    patient_first_name VARCHAR,
    patient_last_name VARCHAR,
    patient_dob VARCHAR,
    external_patient_id VARCHAR,
    external_practice_id VARCHAR,
    code VARCHAR,
    name VARCHAR,
    dictionary_name VARCHAR,
    date_performed VARCHAR,
    date_ordered VARCHAR,
    date_due VARCHAR,
    value VARCHAR,
    medi_unnecessary_reason_code VARCHAR,
    medi_unnecessary_reason_name VARCHAR,
    medi_unnecessary_reason_dict VARCHAR,
    record_verified VARCHAR,
    provider_npi VARCHAR,
    practice_tin VARCHAR,
    provider_name VARCHAR,
    note VARCHAR,
    note_type VARCHAR,
    specimen_source VARCHAR,
    specimen_condition VARCHAR,
    facility_name VARCHAR,
    facility_address VARCHAR,
    received_value VARCHAR,
    received_units VARCHAR,
    low_referance_range VARCHAR,
    high_referance_range VARCHAR,
    abnormal_flag_code VARCHAR,
    remove_specified_lab_flag VARCHAR,
    vendor VARCHAR,
    source_type VARCHAR, 
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/cynchealth/staging/gap_lab',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);
