CREATE TABLE IF NOT EXISTS cynchealth_staging.gap_medication (
    row_id VARCHAR,
    row VARCHAR,
    domain VARCHAR,
    patient_first_name VARCHAR,
    patient_last_name VARCHAR,
    patient_dob VARCHAR,
    external_patient_id VARCHAR,
    external_practice_id VARCHAR,
    code VARCHAR,
    name VARCHAR,
    dictionary_name VARCHAR,
    start_date VARCHAR,
    end_date VARCHAR,
    action_date VARCHAR,
    signed_date VARCHAR,
    form VARCHAR,
    medication_type VARCHAR,
    medi_contraindicated_flag VARCHAR,
    medi_class_contraindicated_flag VARCHAR,    
    dose_value VARCHAR,
    units VARCHAR,
    other VARCHAR,
    schedule VARCHAR,
    notes VARCHAR,
    action VARCHAR,
    refills VARCHAR,
    quantity VARCHAR,
    quantity_unit VARCHAR,
    route_code_text VARCHAR,
    duration VARCHAR,
    substitution_permitted VARCHAR,
    fill_number VARCHAR,
    fill_date VARCHAR,
    source_medication_id VARCHAR,
    stop_reason VARCHAR,
    prescription_id VARCHAR,
    schedule_alternatives VARCHAR,
    deleted VARCHAR,
    source_system VARCHAR,
    vendor VARCHAR,
    source_type VARCHAR,
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/cynchealth/staging/gap_medication',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);
