CREATE TABLE IF NOT EXISTS TENANT_staging.ncqa_hedis_membergm (
    row_id VARCHAR,
    member_id VARCHAR,
    gender VARCHAR,
    date_of_birth VARCHAR,
    member_last_name VARCHAR,
    member_first_name VARCHAR,
    member_middle_initial VARCHAR,
    subscriber_or_family_id_number VARCHAR,
    mailing_address_1 VARCHAR,
    mailing_address_2 VARCHAR,
    city VARCHAR,
    state VARCHAR,
    zip VARCHAR,
    telephone_number VARCHAR,
    parent_caretaker_first_name VARCHAR,
    parent_caretaker_middle_initial VARCHAR,
    parent_caretaker_last_name VARCHAR,
    race VARCHAR,
    ethnicity VARCHAR,
    race_data_source VARCHAR,
    ethnicity_data_source VARCHAR,
    spoken_language VARCHAR,
    spoken_language_source VARCHAR,
    written_language VARCHAR,
    written_language_source VARCHAR,
    other_language VARCHAR,
    other_language_source VARCHAR,
    batch_id VARCHAR,
    source_system VARCHAR,
    file_name VARCHAR,
    status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://DATA_S3_BUCKET/delta-tables/TENANT/staging/ncqa_hedis_membergm',
    PARTITIONED_BY = ARRAY['batch_id'],
    CHECKPOINT_INTERVAL = 5
);