CREATE TABLE IF NOT EXISTS cynchealth_staging.provider (
    row_id VARCHAR,
    physician_npi VARCHAR,
    physician_internal_id VARCHAR,
    physician_work_location_priority VARCHAR,
    physician_first_name VARCHAR,
    physician_last_name VARCHAR,
    physician_middle_initial VARCHAR,
    physician_name_prefix VARCHAR,
    physician_name_suffix VARCHAR,
    physician_degree VARCHAR,
    physician_phone_work VARCHAR,
    physician_phone_mobile VARCHAR,
    physician_email VARCHAR,
    physician_taxonomy_code VARCHAR,
    physician_specialty_code VARCHAR,
    physician_specialty_desc VARCHAR,
    physician_splty_type VARCHAR,
    physician_address_line_1 VARCHAR,
    physician_address_line_2 VARCHAR,
    physician_city VARCHAR,
    physician_state VARCHAR,
    physician_zip VARCHAR,
    physician_contact_title VARCHAR,
    physician_contact_first_name VARCHAR,
    physician_contact_last_name VARCHAR,
    physician_contact_phone VARCHAR,
    physician_contact_email VARCHAR,
    physician_preferred_contact_days VARCHAR,
    physician_preferred_contact_time VARCHAR,
    physician_preferred_contact_method VARCHAR,
    physician_comments VARCHAR,
    provider_org_name VARCHAR,
    provider_org_tin VARCHAR,
    provider_org_group_npi VARCHAR,
    provider_org_internal_id VARCHAR,
    provider_org_location_rank VARCHAR,
    provider_org_lab_id VARCHAR,
    provider_org_lab_name VARCHAR,
    insurance_company_name VARCHAR,
    insurance_company_id VARCHAR,
    physician_participation VARCHAR,
    physician_network_code VARCHAR,
    physician_network_name VARCHAR,
    physician_effective_date TIMESTAMP(3) WITH TIME ZONE,
    physician_termination_date TIMESTAMP(3) WITH TIME ZONE,
    physician_affiliation_status VARCHAR,
    physician_signed_contract VARCHAR,
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/cynchealth/staging/provider',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);
