CREATE TABLE IF NOT EXISTS TENANT_staging.beneficiary (
    row_id VARCHAR,
    member_id VARCHAR,
    member_mbi VARCHAR,
    member_medicaid_id VARCHAR,
    subscriber_id VARCHAR,
    member_id_suffix VARCHAR,
    alternate_member_id VARCHAR,
    member_ssn VARCHAR,
    member_internal_id VARCHAR,
    member_last_name VARCHAR,
    member_first_name VARCHAR,
    member_middle_initial VARCHAR,
    member_name_prefix VARCHAR,
    member_name_suffix VARCHAR,
    member_dob DATE,
    member_gender VARCHAR,
    member_relationship_code VARCHAR,
    member_address_line_1 VARCHAR,
    member_address_line_2 VARCHAR,
    member_city VARCHAR,
    member_county VARCHAR,
    member_state VARCHAR,
    member_zip VARCHAR,
    member_country VARCHAR,
    member_phone_home VARCHAR,
    member_phone_work VARCHAR,
    member_phone_mobile VARCHAR,
    member_email VARCHAR,
    member_deceased_flag VARCHAR,
    member_deceased_date TIMESTAMP(3) WITH TIME ZONE,
    member_primary_language VARCHAR,
    member_race_code VARCHAR,
    member_race_desc VARCHAR,
    member_ethnicity_code VARCHAR,
    member_ethnicity_desc VARCHAR,
    mental_health_flag VARCHAR,
    pharmacy_flag VARCHAR,
    dual_status_code VARCHAR,
    medicare_status_code VARCHAR,
    esrd_dual_eligibility_status VARCHAR,
    esrd_dual_status_code VARCHAR,
    member_risk_score VARCHAR,
    hospice_indicator VARCHAR,
    hospice_start_date TIMESTAMP(3) WITH TIME ZONE,
    hospice_end_date TIMESTAMP(3) WITH TIME ZONE,
    insurance_company_name VARCHAR,
    insurance_company_id VARCHAR,
    insurance_group_name VARCHAR,
    insurance_group_id VARCHAR,
    insurance_group_plan_name VARCHAR,
    insurance_group_plan_id VARCHAR,
    line_of_business VARCHAR,
    insurance_effective_date TIMESTAMP(3) WITH TIME ZONE,
    insurance_end_date TIMESTAMP(3) WITH TIME ZONE,
    insurance_pay_rank VARCHAR,
    provider_org_tin VARCHAR,
    provider_org_name VARCHAR,
    physician_npi VARCHAR,
    physician_internal_id VARCHAR,
    physician_first_name VARCHAR,
    physician_last_name VARCHAR,
    physician_taxonomy_code VARCHAR,
    physician_specialty_code VARCHAR,
    physician_specialty_desc VARCHAR,
    physician_effective_date TIMESTAMP(3) WITH TIME ZONE,
    physician_termination_date TIMESTAMP(3) WITH TIME ZONE,
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://DATA_S3_BUCKET/delta-tables/TENANT/staging/beneficiary',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);
