CREATE TABLE IF NOT EXISTS TENANT_staging.ecw_patientdemographic(
    row_id VARCHAR,
    apuid VARCHAR,
    record_id VARCHAR,
    patient_id VARCHAR,
    patient_account_no VARCHAR,
    name_prefix VARCHAR,
    name_suffix VARCHAR,
    first_name VARCHAR,
    middle_name VARCHAR,
    last_name VARCHAR,
    previous_name VARCHAR,
    date_of_birth DATE,
    gender VARCHAR,
    address_line_1 VARCHAR,
    address_line_2 VARCHAR,
    city VARCHAR,
    state VARCHAR,
    zip VARCHAR,
    marital_status VARCHAR,
    race VARCHAR,
    language VARCHAR,
    ethnic_group VARCHAR,
    primary_phone_number VARCHAR,
    secondary_phone_number VARCHAR,
    primary_email VARCHAR,
    patient_death_indication VARCHAR,
    patient_death_date TIMESTAMP(3) WITH TIME ZONE,
    primary_care_provider_id VARCHAR,
    provider_npi VARCHAR,
    primary_care_provider_last_name VARCHAR,
    primary_care_provider_first_name VARCHAR,
    primary_care_provider_middle_initial VARCHAR,
    primary_care_suffix VARCHAR,
    primary_care_prefix VARCHAR,
    primary_insurance_payor_name VARCHAR,
    primary_insurance_id VARCHAR,
    primary_insurance_payer_code VARCHAR,
    primary_insurance_subscriber_no VARCHAR,
    primary_insurance_medicaid_id VARCHAR,
    primary_insurance_class VARCHAR,
    primary_insurance_start_date TIMESTAMP(3) WITH TIME ZONE,
    primary_insurance_end_date TIMESTAMP(3) WITH TIME ZONE,
    secondary_insurance_payor_name VARCHAR,
    secondary_insurance_id VARCHAR,
    secondary_insurance_payer_code VARCHAR,
    secondary_insurance_subscriber_no VARCHAR,
    secondary_insurance_medicaid_id VARCHAR,
    secondary_insurance_class VARCHAR,
    secondary_insurance_start_date TIMESTAMP(3) WITH TIME ZONE,
    secondary_insurance_end_date TIMESTAMP(3) WITH TIME ZONE,
    tertiary_insurance_payor_name VARCHAR,
    tertiary_insurance_id VARCHAR,
    tertiary_insurance_payer_code VARCHAR,
    tertiary_insurance_subscriber_no VARCHAR,
    tertiary_insurance_medicaid_id VARCHAR,
    tertiary_insurance_class VARCHAR,
    tertiary_insurance_start_date TIMESTAMP(3) WITH TIME ZONE,
    tertiary_insurance_end_date TIMESTAMP(3) WITH TIME ZONE,
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://DATA_S3_BUCKET/delta-tables/TENANT/staging/ecw_patientdemographic',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);