CREATE TABLE IF NOT EXISTS TENANT_staging.ecw_medication (
    row_id VARCHAR,
    apuid VARCHAR,
    record_id VARCHAR,
    item_id VARCHAR,
    patient_id VARCHAR,
    patient_account_no VARCHAR,
    encounter_id VARCHAR,
    provider_id VARCHAR,
    provider_npi VARCHAR,
    medication_origin_id VARCHAR,
    medication_code_system VARCHAR,
    medication_code VARCHAR,
    medication_description VARCHAR,
    prescription_date TIMESTAMP(3) WITH TIME ZONE,
    prescription_begin_date TIMESTAMP(3) WITH TIME ZONE,
    prescription_end_date TIMESTAMP(3) WITH TIME ZONE,
    days_supply VARCHAR,
    quantity VARCHAR,
    refills VARCHAR,
    strength VARCHAR,
    formulation VARCHAR,
    route VARCHAR,
    frequency VARCHAR,
    take VARCHAR,
    medication_status VARCHAR,
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://DATA_S3_BUCKET/delta-tables/TENANT/staging/ecw_medication',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);