CREATE TABLE IF NOT EXISTS TENANT_staging.cclf6 (
    row_id VARCHAR,
    cur_clm_uniq_id INTEGER,
    clm_line_num INTEGER,
    bene_mbi_id VARCHAR,
    bene_hic_num VARCHAR,
    clm_type_cd INTEGER,
    clm_from_dt DATE,
    clm_thru_dt DATE,
    clm_fed_type_srvc_cd VARCHAR,
    clm_pos_cd VARCHAR,
    clm_line_from_dt DATE,
    clm_line_thru_dt DATE,
    clm_line_hcpcs_cd VARCHAR,
    clm_line_cvrd_pd_amt DOUBLE,
    clm_prmry_pyr_cd VARCHAR,
    payto_prvdr_npi_num VARCHAR,
    ordrg_prvdr_npi_num VARCHAR,
    clm_carr_pmt_dnl_cd VARCHAR,
    clm_prcsg_ind_cd VARCHAR,
    clm_adjsmt_type_cd VARCHAR,
    clm_efctv_dt DATE,
    clm_idr_ld_dt DATE,
    clm_cntl_num VARCHAR,
    bene_eqtbl_bic_hicn_num VARCHAR,
    clm_line_alowd_chrg_amt DOUBLE,
    clm_disp_cd VARCHAR,
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://DATA_S3_BUCKET/delta-tables/TENANT/staging/cclf6',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);