CREATE TABLE IF NOT EXISTS TENANT_analytical.patient (
    patient_fhir_id VARCHAR,
    internal_id VARCHAR,
    ssn VARCHAR,
    subscriber_id VARCHAR,
    member_id VARCHAR,
    medicaid_id VARCHAR,
    active BOOLEAN,
    last_name VARCHAR,
    first_name VARCHAR,
    middle_initial VARCHAR,
    name_prefix VARCHAR,
    name_suffix VARCHAR,
    phone_work VARCHAR,
    phone_home VARCHAR,
    phone_mobile VARCHAR,
    email VARCHAR,
    gender VARCHAR,
    birth_date DATE,
    deceased_flag BOOLEAN,
    deceased_date TIMESTAMP(3) WITH TIME ZONE,
    street_line_1 VARCHAR,
    street_line_2 VARCHAR,
    city VARCHAR,
    county VARCHAR,
    state VARCHAR,
    zip VARCHAR,
    country VARCHAR,
    marital_status_code VARCHAR,
    marital_status_desc VARCHAR,
    primary_language_code VARCHAR,
    primary_language_desc VARCHAR,
    practice_fhir_id VARCHAR,
    provider_fhir_id ARRAY(VARCHAR),
    race_code VARCHAR,
    race VARCHAR,
    ethnicity_code VARCHAR,
    ethnicity VARCHAR,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://DATA_S3_BUCKET/delta-tables/TENANT/analytical/patient',
    CHECKPOINT_INTERVAL = 5
);
