CREATE TABLE IF NOT EXISTS nucleo_analytical.medical_claim (
    claim_fhir_id VARCHAR,
    claim_number VARCHAR,
    type_code VARCHAR,
    type_system VARCHAR,
    type_desc VARCHAR,
    use VARCHAR,
    related_ref_value VARCHAR,
    related_ref_system VARCHAR,
    patient_fhir_id VARCHAR,
    billable_start_date TIMESTAMP(3) WITH TIME ZONE,
    billable_end_date TIMESTAMP(3) WITH TIME ZONE,
    created TIMESTAMP(3) WITH TIME ZONE,
    enterer_fhir_id VARCHAR,
    payer_fhir_id VARCHAR,
    provider_fhir_id VARCHAR,
    priority_code VARCHAR,
    priority_system VARCHAR,
    priority_desc VARCHAR,
    funds_reserve_code VARCHAR,
    funds_reserve_system VARCHAR,
    funds_reserve_desc VARCHAR,
    prescription_fhir_id VARCHAR,
    orig_prescription_fhir_id VARCHAR,
    payee_type_code VARCHAR,
    payee_type_desc VARCHAR,
    payee_type_system VARCHAR,
    payee_fhir_id VARCHAR,
    facility_fhir_id VARCHAR,
    diagnosis_sequence VARCHAR,
    diagnosis_fhir_id VARCHAR,
    procedure_sequence VARCHAR,
    procedure_fhir_id VARCHAR,
    insurance_sequence VARCHAR,
    insurance_focal VARCHAR,
    coverage_fhir_id VARCHAR,
    accident_date TIMESTAMP(3) WITH TIME ZONE,
    accident_type_code VARCHAR,
    accident_type_system VARCHAR,
    accident_type_desc VARCHAR,
    accident_address_line_1 VARCHAR,
    accident_address_line_2 VARCHAR,
    accident_city VARCHAR,
    accident_state VARCHAR,
    accident_postal_code VARCHAR,
    location_fhir_id VARCHAR,
    total_amount VARCHAR,
    currency VARCHAR,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/nucleo/analytical/medical_claim',
    CHECKPOINT_INTERVAL = 5
);
