CREATE TABLE IF NOT EXISTS nucleo_analytical.immunization(
    immunization_fhir_id VARCHAR,
    external_id VARCHAR,
    status VARCHAR,
    vaccine_system VARCHAR,
    vaccine_code VARCHAR,
    vaccine_desc VARCHAR,
    patient_fhir_id VARCHAR,
    encounter_fhir_id VARCHAR,
    occurrence_date_time TIMESTAMP(3) WITH TIME ZONE,
    recorded_date_time TIMESTAMP(3) WITH TIME ZONE,
    facility_fhir_id VARCHAR,
    manufacturer_fhir_id VARCHAR,
    lot_number VARCHAR,
    expiration_date DATE,
    site_system VARCHAR,
    site_code VARCHAR,
    site_desc VARCHAR,
    route_system VARCHAR,
    route_code VARCHAR,
    route_desc VARCHAR,
    dose VARCHAR,
    dose_unit VARCHAR,
    dosage_system VARCHAR,
    dosage_code VARCHAR,
    performer_system VARCHAR,
    performer_code VARCHAR,
    performer_display VARCHAR,
    practitioner_fhir_id VARCHAR,
    condition_fhir_id VARCHAR,
    reason_system VARCHAR,
    reason_code VARCHAR,
    reason_desc VARCHAR,
    program_eligibility_system VARCHAR,
    program_eligibility_code VARCHAR,
    program_eligibility_desc VARCHAR,
    provider_fhir_id VARCHAR,
    reason_fhir_id VARCHAR,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/nucleo/analytical/immunization',
    CHECKPOINT_INTERVAL = 5
);