CREATE TABLE IF NOT EXISTS nucleo_analytical.observation (
    observation_fhir_id VARCHAR,
    external_id VARCHAR,
    external_system VARCHAR,
    status VARCHAR,
    category_code VARCHAR,
    category_system VARCHAR,
    category_desc VARCHAR,
    code VARCHAR,
    code_system VARCHAR,
    code_desc VARCHAR,
    patient_fhir_id VARCHAR,
    encounter_fhir_id VARCHAR,
    effective_date_time TIMESTAMP(3) WITH TIME ZONE,
    effective_start_date TIMESTAMP(3) WITH TIME ZONE,
    effective_end_date TIMESTAMP(3) WITH TIME ZONE,
    performer_fhir_id VARCHAR,
    value VARCHAR,
    value_unit VARCHAR,
    value_code VARCHAR,
    value_system VARCHAR,
    value_desc VARCHAR,
    interpretation_code VARCHAR,
    interpretation_system VARCHAR,
    interpretation_desc VARCHAR,
    body_site_code VARCHAR,
    body_site_system VARCHAR,
    body_site_desc VARCHAR,
    method_code VARCHAR,
    method_system VARCHAR,
    method_desc VARCHAR,
    reference_range_low VARCHAR,
    reference_range_high VARCHAR,
    reference_range VARCHAR,
    component_code VARCHAR,
    component_code_system VARCHAR,
    component_code_desc VARCHAR,
    component_value VARCHAR,
    component_value_unit VARCHAR,
    component_value_code VARCHAR,
    component_value_system VARCHAR,
    component_value_desc VARCHAR,
    component_interpretation_code VARCHAR,
    component_interpretation_system VARCHAR,
    component_interpretation_desc VARCHAR,
    component_reference_range_low VARCHAR,
    component_reference_range_high VARCHAR,
    component_reference_range VARCHAR,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/nucleo/analytical/observation',
    CHECKPOINT_INTERVAL = 5
);