CREATE TABLE IF NOT EXISTS nucleo_analytical.patient (
    patient_fhir_id VARCHAR,
    external_id VARCHAR,
    subscriber_id VARCHAR,
    member_id VARCHAR,
    member_mbi VARCHAR,
    medicaid_id VARCHAR,
    active BOOLEAN,
    gender VARCHAR,
    birth_date DATE,
    deceased_flag BOOLEAN,
    deceased_date TIMESTAMP(3) WITH TIME ZONE,
    city VARCHAR,
    county VARCHAR,
    state VARCHAR,
    zip VARCHAR,
    country VARCHAR,
    marital_status_code VARCHAR,
    marital_status_system VARCHAR,
    marital_status_desc VARCHAR,
    primary_language_code VARCHAR,
    primary_language_desc VARCHAR,
    primary_language_syatem VARCHAR,
    practice_fhir_id VARCHAR,
    provider_fhir_id ARRAY(VARCHAR),
    race_code VARCHAR,
    race VARCHAR,
    ethnicity_code VARCHAR,
    ethnicity VARCHAR,
    contact_gender VARCHAR,
    contact_relationship_code VARCHAR,
    contact_relationship_system VARCHAR,
    contact_relationship_desc VARCHAR,
    contact_period_start TIMESTAMP(3) WITH TIME ZONE,
    contact_period_end TIMESTAMP(3) WITH TIME ZONE,
    contact_county VARCHAR,
    contact_state VARCHAR,
    contact_city VARCHAR,
    contact_zip VARCHAR,
    contact_country VARCHAR,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/nucleo/analytical/patient',
    CHECKPOINT_INTERVAL = 5
);
