CREATE TABLE IF NOT EXISTS nucleo_analytical.coverage (
    coverage_fhir_id VARCHAR,
    member_id VARCHAR,
    medicaid_id VARCHAR,
    external_id VARCHAR,
    status VARCHAR,
    kind VARCHAR,
    type_system VARCHAR,
    type_code VARCHAR,
    type_desc VARCHAR,
    subscriber_id VARCHAR,
    patient_fhir_id VARCHAR,
    policy_holder_id VARCHAR,
    subscriber_patient_id VARCHAR,
    dependent VARCHAR,
    relationship_system VARCHAR,
    relationship_code VARCHAR,
    relationship_desc VARCHAR,
    period_start_date TIMESTAMP(3) WITH TIME ZONE,
    period_end_date TIMESTAMP(3) WITH TIME ZONE,
    payer_fhir_id VARCHAR,
    coverage_class_system VARCHAR,
    coverage_class_code VARCHAR,
    coverage_class_desc VARCHAR,
    copay_money_value VARCHAR,
    copay_money_currency VARCHAR,
    copay_quantity_value VARCHAR,
    copay_quantity_unit VARCHAR,
    copay_quantity_system VARCHAR,
    copay_quantity_code VARCHAR,
    copay_type_system VARCHAR,
    copay_type_code VARCHAR,
    copay_type_display VARCHAR,
    coverage_order VARCHAR,
    class_value VARCHAR,
    class_name VARCHAR,
    network VARCHAR,
    plan_fhir_id VARCHAR,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/nucleo/analytical/coverage',
    CHECKPOINT_INTERVAL = 5
);