CREATE TABLE IF NOT EXISTS nucleo_analytical.condition (
    condition_fhir_id VARCHAR,
    external_id VARCHAR,
    clinical_status VARCHAR,
    clinical_status_system VARCHAR,
    clinical_status_desc VARCHAR,
    verification_status VARCHAR,
    verification_status_system VARCHAR,
    verification_status_desc VARCHAR,
    category_code VARCHAR,
    category_desc VARCHAR,
    category_system VARCHAR,
    severity_code VARCHAR,
    severity_code_system VARCHAR,
    severity_code_desc VARCHAR,
    code VARCHAR,
    code_desc VARCHAR,
    code_system VARCHAR,
    bodysite_code VARCHAR,
    bodysite_system VARCHAR,
    bodysite_desc VARCHAR,
    patient_fhir_id VARCHAR,
    encounter_fhir_id VARCHAR,
    onset_start_date TIMESTAMP(3) WITH TIME ZONE,
    onset_end_date TIMESTAMP(3) WITH TIME ZONE,
    abatement_start_date TIMESTAMP(3) WITH TIME ZONE,
    abatement_end_date TIMESTAMP(3) WITH TIME ZONE,
    recorded_date TIMESTAMP(3) WITH TIME ZONE,
    provider_function_code VARCHAR,
    provider_function_system VARCHAR,
    provider_function_desc VARCHAR,
    provider_fhir_id VARCHAR,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/nucleo/analytical/condition',
    CHECKPOINT_INTERVAL = 5
);