CREATE TABLE IF NOT EXISTS nucleo_analytical.medication_request(
    medication_request_fhir_id VARCHAR,
    external_id VARCHAR,
    status VARCHAR,
    intent VARCHAR,
    status_reason_code VARCHAR,
    status_reason_system VARCHAR,
    status_reason_desc VARCHAR,
    category_system VARCHAR,
    category_code VARCHAR,
    category_desc VARCHAR,
    priority VARCHAR,
    medication_code VARCHAR,
    medication_system VARCHAR,
    medication_desc VARCHAR,
    medication_fhir_id VARCHAR,
    patient_fhir_id VARCHAR,
    encounter_fhir_id VARCHAR,
    authored_on TIMESTAMP(3) WITH TIME ZONE,
    provider_fhir_id VARCHAR,
    reason_code VARCHAR,
    reason_system VARCHAR,
    reason_desc VARCHAR,
    validity_period_start_date TIMESTAMP(3) WITH TIME ZONE,
    validity_period_end_date TIMESTAMP(3) WITH TIME ZONE,
    number_of_repeats_allow VARCHAR,
    quantity_value VARCHAR,
    quantity_unit VARCHAR,
    quantity_system VARCHAR,
    quantity_code VARCHAR,
    expected_supply_value VARCHAR,
    expected_supply_unit VARCHAR,
    expected_supply_system VARCHAR,
    expected_supply_code VARCHAR,
    organization_fhir_id VARCHAR,
    dosage_sequence VARCHAR,
    dosage_text VARCHAR,
    additional_instruction_code VARCHAR,
    additional_instruction_system VARCHAR,
    additional_instruction_desc VARCHAR,
    patient_instruction VARCHAR,
    dosage_frequency VARCHAR,
    dosage_duration VARCHAR,
    dosage_period_unit VARCHAR,
    route_code VARCHAR,
    route_system VARCHAR,
    route_desc VARCHAR,
    site_code VARCHAR,
    site_system VARCHAR,
    site_desc VARCHAR,
    dosage_type_code VARCHAR,
    dosage_type_system VARCHAR,
    dosage_type_desc VARCHAR,
    dose_quantity_value VARCHAR,
    dose_quantity_unit VARCHAR,
    dose_rate_quantity_value VARCHAR,
    dose_rate_quantity_unit VARCHAR,
    dose_range_low VARCHAR,
    dose_range_high VARCHAR,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://phm-development-datapipeline-bucket/delta-tables/nucleo/analytical/medication_request',
    CHECKPOINT_INTERVAL = 5
);