diagnois_patient_id:
  key_path: patient_id
  min_length: 1
  required: True

diagnois_provider_npi:
  key_path: provider_npi
  required: True
  type: string
  min_length: 10

diagnois_encounter_id:
  key_path: encounter_id
  required: True
  type: string
  min_length: 1
