facility_zip_code:
  key_path: address_zip
  min_length: 10
  type: string

facility_name:
  key_path: facility_name
  type: string
  min_length: 1

facility_practice_apuid:
  key_path: apuid
  type: string
  required: True
