patient_demographic_provider_npi:
  key_path: provider_npi
  required: True
  type: string
  min_length: 10

patient_demographic_practice_apuid:
  key_path: apuid
  type: string
  required: True

patient_demographic_zip_code:
  key_path: address_zip
  min_length: 10
  type: string
