CREATE TABLE IF NOT EXISTS TENANT_staging.practice (
    row_id VARCHAR,
    provider_org_name VARCHAR,
    provider_org_dba_name VARCHAR,
    provider_org_type VARCHAR,
    provider_org_location_rank VARCHAR,
    provider_org_taxonomy_code VARCHAR,
    provider_org_ssn VARCHAR,
    provider_org_tin VARCHAR,
    provider_org_group_npi VARCHAR,
    provider_org_internal_id VARCHAR,
    provider_org_napb_id VARCHAR,
    provider_org_address_line_1 VARCHAR,
    provider_org_address_line_2 VARCHAR,
    provider_org_city VARCHAR,
    provider_org_county VARCHAR,
    provider_org_state VARCHAR,
    provider_org_zip VARCHAR,
    provider_org_country VARCHAR,
    provider_org_phone_work VARCHAR,
    provider_org_email VARCHAR,
    provider_org_fax VARCHAR,
    provider_org_lab_id VARCHAR,
    provider_org_lab_name VARCHAR,
    provider_org_contact_title VARCHAR,
    provider_org_contact_first_name VARCHAR,
    provider_org_contact_last_name VARCHAR,
    provider_org_contact_middle_name VARCHAR,
    provider_org_contact_phone VARCHAR,
    provider_org_contact_email VARCHAR,
    insurance_company_name VARCHAR,
    insurance_company_id VARCHAR,
    file_batch_id VARCHAR,
    file_name VARCHAR,
    file_source_name VARCHAR,
    file_status VARCHAR,
    created_user VARCHAR,
    created_ts TIMESTAMP(3) WITH TIME ZONE,
    updated_user VARCHAR,
    updated_ts TIMESTAMP(3) WITH TIME ZONE
)
WITH (
    LOCATION = 's3a://DATA_S3_BUCKET/delta-tables/TENANT/staging/practice',
    PARTITIONED_BY = ARRAY['file_batch_id'],
    CHECKPOINT_INTERVAL = 5
);
